# Generated by Django 4.2.17 on 2024-12-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_button',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_emails',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_phone_numbers',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
