# Generated by Django 4.2.17 on 2025-01-03 14:18

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_alter_plan_max_button_alter_plan_max_emails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Title', help_text='The title of the content.', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text="Unique identifier for the content (e.g., 'terms-and-conditions').", max_length=255, unique=True)),
                ('body', ckeditor.fields.RichTextField(default='Default body content.', help_text='The content to display, supports rich text formatting.')),
                ('meta_title', models.CharField(blank=True, help_text='Optional meta title for SEO. Defaults to the title.', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Optional meta description for SEO.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the content was created.')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the content was last updated.')),
            ],
            options={
                'verbose_name': 'Email Content',
                'verbose_name_plural': 'Email Contents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
