# Generated by Django 4.2.17 on 2025-01-08 11:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0006_alter_baseuser_plan_alter_paymenthistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontent',
            name='body_en',
            field=ckeditor.fields.RichTextField(help_text='The content to display, supports rich text formatting.', null=True),
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='body_hi',
            field=ckeditor.fields.RichTextField(help_text='The content to display, supports rich text formatting.', null=True),
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Optional meta description for SEO.', null=True),
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='meta_description_hi',
            field=models.TextField(blank=True, help_text='Optional meta description for SEO.', null=True),
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Optional meta title for SEO. Defaults to the title.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='meta_title_hi',
            field=models.CharField(blank=True, help_text='Optional meta title for SEO. Defaults to the title.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='title_en',
            field=models.CharField(help_text='The title of the content.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='title_hi',
            field=models.CharField(help_text='The title of the content.', max_length=255, null=True, unique=True),
        ),
    ]
