# Generated by Django 4.2.17 on 2025-01-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0007_staticcontent_body_en_staticcontent_body_hi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticcontent',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='staticcontent',
            name='body_hi',
        ),
        migrations.RemoveField(
            model_name='staticcontent',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='staticcontent',
            name='meta_description_hi',
        ),
        migrations.RemoveField(
            model_name='staticcontent',
            name='meta_title_en',
        ),
        migrations.RemoveField(
            model_name='staticcontent',
            name='meta_title_hi',
        ),
        migrations.RemoveField(
            model_name='staticcontent',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='staticcontent',
            name='title_hi',
        ),
    ]
