# Generated by Django 4.2.17 on 2025-01-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0009_blogimage_bulletedpoint_tag_profile_blogpost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='WhatsApp URL')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
            ],
            options={
                'verbose_name': 'Follow Us Link',
                'verbose_name_plural': 'Follow Us Links',
            },
        ),
    ]
