# Generated by Django 4.2.17 on 2025-01-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0010_followus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followus',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='followus',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='followus',
            name='pinterest',
            field=models.URLField(blank=True, null=True, verbose_name='Pinterest URL'),
        ),
        migrations.AddField(
            model_name='followus',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram URL'),
        ),
    ]
