# Generated by Django 4.2.17 on 2025-01-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0011_remove_followus_linkedin_remove_followus_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology & Innovation'), ('cyber', 'Cybersecurity'), ('disaster', 'Disaster Preparedness'), ('business', 'Business & Entrepreneurship'), ('safety', 'Personal Safety & Security'), ('health', 'Health & Wellness'), ('lifestyle', 'Lifestyle & Productivity'), ('community', 'Community Engagement & Social Impact'), ('tutorials', 'Tech Reviews & Tutorials'), ('environmental', 'Environmental Sustainability')], default='general', max_length=50),
        ),
    ]
