# Generated by Django 4.2.17 on 2024-12-19 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sosphones',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_phones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sosemails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.device'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.event'),
        ),
        migrations.AddIndex(
            model_name='getintouch',
            index=models.Index(fields=['email'], name='core_getint_email_0502ac_idx'),
        ),
        migrations.AddIndex(
            model_name='getintouch',
            index=models.Index(fields=['phone_number'], name='core_getint_phone_n_72ed7e_idx'),
        ),
        migrations.AddField(
            model_name='event',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.device'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicevideo',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.device'),
        ),
        migrations.AddField(
            model_name='devicevideo',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devicevideo', to='core.event'),
        ),
        migrations.AddField(
            model_name='devicevideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicestream',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device'),
        ),
        migrations.AddField(
            model_name='device',
            name='sos_emails',
            field=models.ManyToManyField(blank=True, related_name='devices', to='core.sosemails'),
        ),
        migrations.AddField(
            model_name='device',
            name='sos_phones',
            field=models.ManyToManyField(blank=True, related_name='devices', to='core.sosphones'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sosphones',
            index=models.Index(fields=['user', 'phone_numbers'], name='core_sospho_user_id_13ed0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sosphones',
            unique_together={('user', 'phone_numbers')},
        ),
        migrations.AddIndex(
            model_name='sosemails',
            index=models.Index(fields=['user', 'emails'], name='core_sosema_user_id_8da166_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sosemails',
            unique_together={('user', 'emails')},
        ),
        migrations.AlterUniqueTogether(
            name='devicestream',
            unique_together={('device',)},
        ),
    ]
