# Generated by Django 4.2.17 on 2024-12-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestream',
            name='is_stream',
            field=models.BooleanField(default=True),
        ),
    ]
