# Generated by Django 4.2.17 on 2025-01-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0013_remove_blogcomment_blog_and_more'),
        ('core', '0003_devicestream_is_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=150, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customadmin.user')),
            ],
            options={
                'db_table': 'tenant_table',
            },
        ),
    ]
