# Generated by Django 4.2.17 on 2025-01-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
