# Generated by Django 4.2.17 on 2025-01-13 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_extra_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BulletedPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='bulleted_images/')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram URL')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('pinterest', models.URLField(blank=True, null=True, verbose_name='Pinterest URL')),
            ],
            options={
                'verbose_name': 'Follow Us Link',
                'verbose_name_plural': 'Follow Us Links',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('designation', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('category', models.CharField(choices=[('tech', 'Technology & Innovation'), ('cyber', 'Cybersecurity'), ('disaster', 'Disaster Preparedness'), ('business', 'Business & Entrepreneurship'), ('safety', 'Personal Safety & Security'), ('health', 'Health & Wellness'), ('lifestyle', 'Lifestyle & Productivity'), ('community', 'Community Engagement & Social Impact'), ('tutorials', 'Tech Reviews & Tutorials'), ('environmental', 'Environmental Sustainability')], default='general', max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('quote_text', models.CharField(blank=True, max_length=500, null=True)),
                ('extra_content', models.TextField(blank=True, null=True)),
                ('bulleted_points', models.ManyToManyField(blank=True, related_name='blog_posts', to='blogs.bulletedpoint')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.profile')),
                ('extra_images', models.ManyToManyField(blank=True, related_name='posts', to='blogs.blogimage')),
                ('quote_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='blogs.profile')),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_posts', to='blogs.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blogpost')),
            ],
        ),
    ]
