# Generated by Django 4.2.17 on 2025-01-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogpost_created_by_alter_blogpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology & Innovation'), ('cyber', 'Cybersecurity'), ('disaster', 'Disaster Preparedness'), ('business', 'Business & Entrepreneurship'), ('safety', 'Personal Safety & Security'), ('health', 'Health & Wellness'), ('lifestyle', 'Lifestyle & Productivity'), ('community', 'Community Engagement'), ('tutorials', 'Tech Reviews & Tutorials'), ('environmental', 'Environmental Sustainability')], default='general', max_length=50),
        ),
    ]
